---
# vars file for vs_code_setup
v_vs_code_setup_username: "required"
v_vs_code_setup_color_scheme: "required"
v_vs_code_setup_ansible_default_execution_environment_image: "required"
v_vs_code_setup_ansible_lint_config_file: "required"
v_vs_code_setup_extensions: []
v_vs_code_setup_rootdir: "required"
