---
- name: Update Before Main Packages
  ansible.builtin.apt:
    update_cache: true

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install Main Packages
  ansible.builtin.apt:
    name: "{{ install_main_packages_package_item }}"
    state: present
  loop:
    - "{{ v_install_main_packages_install_list }}"
  loop_control:
    loop_var: install_main_packages_package_item
